name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "023ec884-4ca6-4cff-acb8-40fcedda1d65"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "notes-kv"
preview_id = "2e9ebbaf0d134902a43076bd49aa930b"

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
